---
- hosts: dev
  become: yes
  become_method: sudo
  remote_user: root
  tasks:
    - name: Install python pip
      ansible.builtin.package:
        name: python-pip
        state: present
    - name: Install docker-py python module
      ansible.builtin.pip:
        name:
          - docker-py
        state: present
    - name: Start the container
      community.docker.docker_container:
        name: customer-service
        image: "anunnakish/customer-service:{{DOCKER_TAG}}"
        state: started
        published_ports:
          - 0.0.0.0:8081:8081